"use client";
import { useState } from 'react';
import { CakeSlice, ArrowUpRight, Phone, MapPin, Menu, X } from 'lucide-react';
import {Benefits,About,Offer,Cakes,OrderSteps,Gallery,OrderForm,Contact,Footer,BusinessSchema} from './sections';
import {assetPath} from '@/lib/assets';
const links = [['Start','start'],['O nas','o-nas'],['Oferta','oferta'],['Torty','torty'],['Galeria','galeria'],['Kontakt','kontakt']];
export function Navbar(){const [open,setOpen]=useState(false);return <header className="navbar"><a className="brand" href="#start"><CakeSlice/><span>Cukiernia Wrocławska<small>RAFAŁ I BENEDYKT MENCEL</small></span></a><nav className={open?'navigation open':'navigation'} aria-label="Nawigacja główna">{links.map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setOpen(false)}>{label}</a>)}</nav><a className="button nav-cta" href="#zapytanie">Zapytaj o tort <ArrowUpRight size={17}/></a><button className="menu-toggle" aria-label={open?'Zamknij menu':'Otwórz menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>}
export function Hero(){return <section id="start" className="hero wrap"><div className="hero-copy"><p className="eyebrow">CUKIERNIA WROCŁAWSKA · OLESNO</p><h1>Słodkości przygotowywane na <em>wyjątkowe chwile</em></h1><p className="intro">Torty, ciasta i wypieki tworzone z myślą o rodzinnych uroczystościach, spotkaniach i chwilach, które warto celebrować.</p><div className="actions"><a className="button" href="#zapytanie">Zapytaj o tort <ArrowUpRight size={19}/></a><a className="text-link" href="#oferta">Zobacz nasze wypieki <span>→</span></a></div><div className="hero-details"><span><MapPin size={16}/> ul. Adama Mickiewicza 4, Olesno</span><a href="tel:343583632"><Phone size={16}/>34 358 36 32</a></div></div><div className="hero-photo"><img src={assetPath('/images/hero.jpg')} alt="Przykładowy tort z kremem, truskawkami i borówkami" fetchPriority="high"/><div className="photo-note"><CakeSlice size={27}/><span>Małe przyjemności.<br/><strong>Wielkie okazje.</strong></span></div><span className="image-caption">ZDJĘCIE INSPIRACYJNE</span></div></section>}
export default function Home(){return <><a className="skip-link" href="#main">Przejdź do treści</a><Navbar/><main id="main"><Hero/><Benefits/><About/><Offer/><Cakes/><OrderSteps/><Gallery/><OrderForm/><Contact/></main><Footer/><BusinessSchema/></>}


